=== DaveTheDudeFromECAM/WebArchitectureProjects/XML/XML XSD/XSD_20323.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:simpleType name="TimeType">
    <xsd:restriction base="xsd:string">
        <xsd:enumeration value="minutes"/>
        <xsd:enumeration value="hours"/>
        <xsd:enumeration value="seconds"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:complexType name="guide_Time">
    <xsd:simpleContent>
        <xsd:extension base="xsd:integer">
            <xsd:attribute name="unity" type="TimeType" />
        </xsd:extension> 
    </xsd:simpleContent>
</xsd:complexType>
<xsd:complexType name="Ingredient_type">
    <xsd:simpleContent>
        <xsd:extension base="xsd:float">
            <xsd:attribute name="name" type="xsd:string"/>
            <xsd:attribute name="unity" type="xsd:string"/>
        </xsd:extension> 
    </xsd:simpleContent>
</xsd:complexType>
<xsd:complexType name="Dietetic_type">
    <xsd:simpleContent>
        <xsd:extension base="xsd:integer">
            <xsd:attribute name="unity" type="xsd:string"/>
        </xsd:extension> 
    </xsd:simpleContent>
</xsd:complexType>
<xsd:element name="Recipe">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string" minOccurs="1"/>
            <xsd:element name="image" type="xsd:string" minOccurs="0"/>
            <xsd:element name="autor" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name ="Lastname" type="xsd:string"/>
                        <xsd:element name ="Firstname" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="description" type="xsd:string" minOccurs="1"/>
            <xsd:element name="guide" minOccurs="1">   
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name ="Time">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="Preparation" type="guide_Time" minOccurs="0" /> 
                                    <xsd:element name="Cooking" type="guide_Time" minOccurs="0"/>
                                    <xsd:element name="rest" type="guide_Time" minOccurs="0"/>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name ="difficulty" type="xsd:string" minOccurs="0"/>
                        <xsd:element name ="people" minOccurs="0">
                            <xsd:complexType>
                                <xsd:simpleContent>
                                    <xsd:extension base="xsd:integer">
                                        <xsd:attribute name="unity" type="xsd:string"/>
                                    </xsd:extension> 
                                </xsd:simpleContent>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Ingredients" minOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Ingredient" type="Ingredient_type" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="Preperation" minOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name ="Step" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="dietetic" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="portion" type="Dietetic_type" minOccurs="0"/>
                        <xsd:element name="Nutritional_value" type="Dietetic_type" minOccurs="0"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="tips" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>
</xsd:schema>

=== DaveTheDudeFromECAM/WebArchitectureProjects/XML/XML XSD/Recette1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Recipe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD_20323.xsd">
    <title>Fondant au chocolat ultra facile</title>

    <image></image>

    <description>Dessert - Facile - Bon marché - Végétarien</description>

    <guide>
        <Time>
            <Preparation unity = "minutes">5</Preparation>
            <Cooking unity = "minutes">7</Cooking>
        </Time>
    </guide>

    <Ingredients>
        <Ingredient name = "chocolate" unity = "gram">600</Ingredient>
        <Ingredient name = "sugar" unity = "gram">200</Ingredient>
        <Ingredient name = "egg" unity = "number">8</Ingredient>
    </Ingredients>
    
    <Preperation>
        <Step>Préchauffer le four à 210°C (thermostat 7).</Step>
        <Step>Faire fondre le chocolat au bain-marie.</Step>
        <Step>Pendant ce temps, mélanger les oeufs, le sucre et faire blanchir.</Step>
        <Step>Quand le chocolat est fondu, l'incorporer au mélange oeufs et sucre.</Step>
        <Step>Beurrer un moule à manqué ou des moules individuels (de préférence en silicone) et y verser la préparation.</Step>
        <Step>Faire cuire le fondant pendant environ 7 à 10 minutes.</Step>
        <Step>Attention, vérifier la cuisson en plantant la pointe du couteau au milieu du fondant.</Step>
    </Preperation>

</Recipe>

=== DaveTheDudeFromECAM/WebArchitectureProjects/XML/XML XSD/Recette3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Recipe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD_20323.xsd">
    <title>Recette Soufflé léger au chou-fleur</title>
    <image></image>
    <autor>
        <Lastname>Bonneau</Lastname>
        <Firstname>Isabelle</Firstname>
    </autor>
    <description>Ce soufflé est très facile à réaliser, très léger et moelleux, un bon accompagnement pour viandes et poissons !</description>
    <guide>
        <Time>
            <Preparation unity = "minutes">20</Preparation>
            <Cooking unity = "minutes">40</Cooking>
        </Time>
        <difficulty>Facile</difficulty>
        <people unity = "number">4</people>
    </guide>
    <Ingredients>
        <Ingredient name = "cauliflower" unity = "gram">600</Ingredient>
        <Ingredient name = "20% cottage cheese" unity = "gram">200</Ingredient> 
        <Ingredient name = "grated cheese" unity = "gram">40</Ingredient>
        <Ingredient name = "egg" unity = "number">2</Ingredient>
        <Ingredient name = "freshly grated nutmeg" unity = "number">1</Ingredient>
        <Ingredient name = "sel" unity = "pinch">1</Ingredient>
        <Ingredient name = "pepper" unity = "pinch">1</Ingredient>
    </Ingredients>
    
    <Preperation>
        <Step>Faites cuire le chou-fleur à la vapeur après l'avoir lavé. Préchauffez votre four à 180°C.</Step>
        <Step>Séparez les blancs des jaunes d'oeufs. Mixez le chou-fleur avec les jaunes et le fromage blanc. Salez, poivrez et ajoutez la noix de muscade ainsi que le fromage râpé.</Step>
        <Step>Montez les blancs d'oeufs en neige et incorporez-les délicatement au chou-fleur.</Step>
        <Step>Versez le tout dans un plat allant au four ou 4 petits plats individuels et faites cuire au four à 180°c entre 25 et 30 minutes. N'ouvrez surtout pas la porte du four avant la fin de la cuisson, le soufflé retomberait !</Step>
    </Preperation>
    <tips>Servez chaud dès que le dessus est doré.</tips>
</Recipe>
